FROM alpine:3.14

RUN  apk update && apk upgrade && \
     apk add apache2 && \
     apk add apache2-proxy && \
     apk add apache2-ssl && \
     rm -rf /var/cache/apk/*

COPY /conf.d/* /etc/apache2/
COPY /html/ /var/www/localhost/htdocs

CMD  [ "/usr/sbin/httpd", "-D", "FOREGROUND"]

#https://www.sentiatechblog.com/running-apache-in-a-docker-container
#https://github.com/sentialabs/scarlet
